name: hola-mundo
#Es el nombre del Workflow que aparecerá en la sección de Actions en Github (opcional pero recomendadisimo).

run-name: Estoy aprendiendo GitHub Actions!
# Es el nombre específico del Workflow que aparecerá en la pestaña de Actions en Github (Opcional).

on: [push]
#Esta se divide en 2. El “on” será la etiqueta que determine los triggers por los que se 
# activará el Workflow; el [push] será el trigger por el que ha sido activado. Como es una lista, puedes agregar más triggers.

jobs: #Agrupará todos los jobs que ocurrirán en el Workflow (no contiene valor).
  hola-mundo:
    #Esta es el identificador del job, así se diferenciará del resto 
    #(no puede contener espacios).
    runs-on: ubuntu-latest #Especificará el tipo de Runner para este job.
    steps: 
      #Agrupará todos los steps del job. Existen 2 tipos de steps, los que correrán actions del 
      #Marketplace o comandos de shell.
      - name: Checkout
      #Nombre del step, su identificador. (también es opcional pero es recomendado usarla).
        uses: actions/checkout@v4
        #En este caso se usa la etiqueta uses para importar un action.

      
      - name: Definir variable
        run: echo "USERNAME=${{ github.actor}}" >> $GITHUB_ENV

      - name: Correr Script
        run: python hola_mundo.py
        #En este otro caso se usa la etiqueta run para correr un comando o script.
